version: '3'

services:
  client:
    container_name: todo-vue
    build: ./client
    image: web-ui
    ports:
      - 8080:8080
    volumes:
      - ./client:/src:cached
    tty: true
    command: yarn serve

  api:
    container_name: todo-go
    links: 
      - db
    build: ./api
    image: golang:1.15
    ports:
      - 8888:8888
    volumes:
      - ./api:/api:cached
    tty: true
    command: go run main.go
  
  db:
    container_name: todo-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: todo-db
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql:cached
      - ./db/my.cnf:/etc/mysql/my.cnf:cached
      - ./db/init/:/docker-entrypoint-initdb.d:cached